### ISSUE TITLE
Example code crashes with SIGABRT

### ISSUE THREAD

**Issue by cloudify** [FedericoCeratto/nim-syslog#5]
On OSX 10.11.6:

```
% nim c -r test_syslog.nim
Hint: used config file '/usr/local/Cellar/nim/0.15.2/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test_syslog [Processing]
Hint: syslog [Processing]
Hint: posix [Processing]
Hint: times [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: os [Processing]
CC: test_syslog
CC: stdlib_system
CC: syslog
CC: stdlib_posix
CC: stdlib_times
CC: stdlib_strutils
CC: stdlib_parseutils
CC: stdlib_math
CC: stdlib_algorithm
CC: stdlib_os
Hint:  [Link]
Hint: operation successful (21624 lines compiled; 1.730 sec total; 29.004MiB; Debug Build) [SuccessX]
Hint: ~/src/test_syslog  [Exec]
Traceback (most recent call last)
syslog.nim(137)          syslog
SIGABRT: Abnormal termination.
Error: execution of an external program failed: '~/src/test_syslog '
```

Tries also with `sudo`, same error.

**Comment by cloudify** [comment]
The error happens on this line:

```nim
var sock_addr {.global.}: SockAddr = SockAddr(sa_family: posix.AF_UNIX, sa_data: syslog_socket_fname_a)
```

I'm not 100% confident on this (my C skills are a bit rusted) but can it be due to the difference in how `SockAddr` is defined in `posix.nim` vs `socket.h`?

From `posix.nim`:

```nim
  SockAddr* {.importc: "struct sockaddr", header: "<sys/socket.h>",
              pure, final.} = object ## struct sockaddr
    sa_family*: TSa_Family         ## Address family.
    sa_data*: array[0..255, char] ## Socket address (variable-length data).
```

From `sys/socket.h`:

```C
struct sockaddr {
	__uint8_t	sa_len;		/* total length */
	sa_family_t	sa_family;	/* [XSI] address family */
	char		sa_data[14];	/* [XSI] addr value (actually larger) */
};
```

`sa_len` is missing from the Nim code.

**Comment by FedericoCeratto** [comment]
@goldenreign are you aware of this? Anyhow, I'm adding OSX builds to Travis CI

**Comment by goldenreign** [comment]
This is the issue for Linux too. We should use [`Sockaddr_un`](https://github.com/nim-lang/Nim/blob/01ae0d28d47ef4cdd26e1f1f04e40aa9ae6ffe2b/lib/posix/posix.nim#L468) instead of [`SockAddr`](https://github.com/nim-lang/Nim/blob/01ae0d28d47ef4cdd26e1f1f04e40aa9ae6ffe2b/lib/posix/posix.nim#L463).

`posix.nim` has a bug too [here](https://github.com/nim-lang/Nim/blob/01ae0d28d47ef4cdd26e1f1f04e40aa9ae6ffe2b/lib/posix/posix.nim#L466) because `sys/socket.h` defines `char sa_data[14];`. And basically what we have done is passing 256-byte array to 14-byte buffer.

I tested new code on Ubuntu. @cloudify could you please check if PR #6 fixes the issue on OS X too?

BTW CI seams to be not working yet.

**Comment by cloudify** [comment]
@goldenreign yes PR #6 fixes the issue for me, I confirm that it works now on OSX 10.11.6

Thanks!
